[versions]
agp = "8.6.0-alpha08"
kotlin = "2.0.0"
coreKtx = "1.13.1"
junit-jupiter ="5.10.3"
espressoCore = "3.6.1"
junitVersion = "1.2.1"
appcompat = "1.7.0"
dokka = "1.9.20"
material = "1.12.0"
detekt = "1.23.6"
compose = "2024.06.00"
timber-version = "5.0.1"
kover = "0.8.2"
collectSarifVersion = "1.0.0"
detectComposeVersion = "0.0.26"
uiGraphicsAndroid = "1.6.8"
foundationAndroid = "1.6.8"
material3Android = "1.2.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }
detekt-compose = { module = "com.twitter.compose.rules:detekt", version.ref = "detect-compose-version" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber-version" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-material = { module = "androidx.compose.material:material" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-activity = { module = "androidx.activity:activity-compose" }
androidx-material3-android = { module = "androidx.compose.material3:material3"}
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gitlab-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
jetbrains-kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
collect-sarif = { id = "collect-sarif", version.ref = "collectSarifVersion" }
merge-sarif = { id = "merge-sarif", version.ref = "collectSarifVersion" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
